### ISSUE TITLE
使用 Bilibili 移动客户端增强 过滤器时会导致视频加载失败

### ISSUE THREAD

**Issue by ShadowLyin** [Kr328/AdGuard-Custom-Rule#1]
录屏：https://drive.google.com/file/d/18FIUzXToUxQXzJYShaZE_7P1RaOty-GT/view?usp=sharing
Adguard 版本：v3.0.297 (1.3.207cl)
哔哩哔哩版本：5.39.1

**Comment by Kr328** [comment]
尝试 更新 新的规则
以及 阅读 新的 Bilibili 规则说明
